SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM cast_person;

INSERT INTO cast_person (cast_id, name, role_type, cast_url) VALUES
(1, 'Băng Di', 'ACTOR', '/assets/images/actors/avatars/Bang_Di.jpg'),
(2, 'Khương Ngọc', 'DIRECTOR', null),
(3, 'Hồng Đào', 'ACTOR','/assets/images/actors/avatars/Hong_Dao.jpg'),
(4, 'Hữu Châu', 'ACTOR','/assets/images/actors/avatars/Huu_Chau.jpg'),
(5, 'Lâm Thanh Mỹ', 'ACTOR','/assets/images/actors/avatars/Lam_Thanh_My.jpg'),
(6, 'Việt Hương', 'ACTOR','/assets/images/actors/avatars/Viet_Huong.jpg'),
(7, 'Anh Tú Atus', 'ACTOR','/assets/images/actors/avatars/Anh_Tu_Atus.jpg'),
(8, 'Trần Hữu Tấn', 'DIRECTOR', null),
(9, 'Hoàng Linh Chi', 'ACTOR','/assets/images/actors/avatars/Hoang_Linh_Chi.jpg'),
(10, 'Lương Thế Thành', 'ACTOR','/assets/images/actors/avatars/Luong_The_Thanh.png'),
(11, 'Huỳnh Thanh Trực', 'ACTOR','/assets/images/actors/avatars/Huynh_Thanh_Truc.jpg'),
(12, 'Rima Thanh Vy', 'ACTOR','/assets/images/actors/avatars/Rima_Thanh_Vy.jpeg'),
(13, 'Giovanni Ribisi', 'ACTOR','/assets/images/actors/avatars/Giovanni_Ribisi.jpg'),
(14, 'James Cameron', 'DIRECTOR', null),
(15, 'Kate Winslet', 'ACTOR','/assets/images/actors/avatars/Kate_Winslet.jpg'),
(16, 'Zoe Saldaña', 'ACTOR','/assets/images/actors/avatars/Zoe_Saldaña.jpg'),
(17, 'Diane Lane', 'ACTOR','/assets/images/actors/avatars/Diane_Lane.jpg'),
(18, 'Jan Komasa', 'DIRECTOR', null),
(19, 'Kyle Chandler', 'ACTOR','/assets/images/actors/avatars/Kyle_Chandler.jpg'),
(20, 'Zoey Deutch', 'ACTOR','/assets/images/actors/avatars/Zoey_Deutch.jpg'),
(21, 'Phoebe Dynevor', 'ACTOR','/assets/images/actors/avatars/Phoebe_Dynevor.jpg'),
(22, 'Lương Gia Huy', 'ACTOR','/assets/images/actors/avatars/Luong_Gia_Huy.jpeg'),
(23, 'Hoàng Thơ', 'DIRECTOR', null),
(24, 'Thái Trà My', 'ACTOR','/assets/images/actors/avatars/Thai_Tra_My.jpg'),
(25, 'Dũng Bino', 'ACTOR','/assets/images/actors/avatars/Dung_Bino.jpg'),
(26, 'Bích Ngọc', 'ACTOR','/assets/images/actors/avatars/Bich_Ngoc.jpg'),
(27, 'Ethan Hawke', 'ACTOR','/assets/images/actors/avatars/Ethan_Hawke.jpg'),
(28, 'Scott Derrickson', 'DIRECTOR', null),
(29, 'Mason Thames', 'ACTOR','/assets/images/actors/avatars/Mason_Thames.jpg'),
(30, 'Madeleine McGraw', 'ACTOR','/assets/images/actors/avatars/Madeleine_McGraw.jpg'),
(31, 'Demián Bichir', 'ACTOR','/assets/images/actors/avatars/Demián_Bichir.jpg'),
(32, 'Arianna Rivas', 'ACTOR','/assets/images/actors/avatars/Arianna_Rivas.jpg'),
(33, 'G-DRAGON', 'ACTOR','/assets/images/actors/avatars/G-DRAGON.jpg'),
(34, 'JINHO BYUN', 'DIRECTOR', null),
(35, 'TAEYANG', 'ACTOR','/assets/images/actors/avatars/TAEYANG.jpeg'),
(36, 'DAESUNG', 'ACTOR','/assets/images/actors/avatars/DAESUNG.jpg'),
(37, 'CL', 'ACTOR','/assets/images/actors/avatars/CL.jpg'),
(38, 'Yunita Siregar', 'ACTOR','/assets/images/actors/avatars/Yunita_Siregar.jpg'),
(39, 'Hadrah Daeng Ratu', 'DIRECTOR', null),
(40, 'Dinda Kanyadewi', 'ACTOR','/assets/images/actors/avatars/Dinda_Kanyadewi.jpg'),
(41, 'Tarra Budiman', 'ACTOR','/assets/images/actors/avatars/Tarra_Budiman.jpeg'),
(42, 'Mckenna Grace', 'ACTOR','/assets/images/actors/avatars/Mckenna_Grace.jpg'),
(43, 'Emma Tammi', 'DIRECTOR', null),
(44, 'Josh Hutcherson', 'ACTOR','/assets/images/actors/avatars/Josh_Hutcherson.jpg'),
(45, 'Matthew Lillard', 'ACTOR','/assets/images/actors/avatars/Matthew_Lillard.jpg'),
(46, 'Quang Tuấn', 'ACTOR','/assets/images/actors/avatars/Quang_Tuan.jpg'),
(47, 'Trương Dũng', 'DIRECTOR', null),
(48, 'Huỳnh Đông', 'ACTOR','/assets/images/actors/avatars/Huynh_Dong.jpg'),
(49, 'Vân Trang', 'ACTOR','/assets/images/actors/avatars/Van_Trang.jpg'),
(50, 'Hoàng Kim Ngọc', 'ACTOR','/assets/images/actors/avatars/Hoang_Kim_Ngoc.jpg'),
(51, 'Lan Thy', 'ACTOR','/assets/images/actors/avatars/Lan_Thy.jpg'),
(52, 'Ái Như', 'ACTOR','/assets/images/actors/avatars/Ai_Nhu.jpg'),
(53, 'Nguyễn Thanh Bình', 'DIRECTOR', null),
(54, 'Huy Khánh', 'ACTOR','/assets/images/actors/avatars/Huy_Khanh.jpg'),
(55, 'Tín Nguyễn', 'ACTOR','/assets/images/actors/avatars/Tin_Nguyen.jpg'),
(56, 'Bé Sam', 'ACTOR','/assets/images/actors/avatars/Be_Sam.jpg'),
(57, 'Ngọc Sơn', 'ACTOR','/assets/images/actors/avatars/Ngoc_Son.jpg'),
(58, 'Jason Bateman', 'ACTOR','/assets/images/actors/avatars/Jason_Bateman.jpg'),
(59, 'Jared Bush', 'DIRECTOR', null),
(60, 'Quinta Brunson', 'ACTOR','/assets/images/actors/avatars/Quinta_Brunson.jpg'),
(61, 'Byron Howard', 'DIRECTOR', null),
(62, 'Fortune Feimster', 'ACTOR','/assets/images/actors/avatars/Fortune_Feimster.jpg'),
(63, 'Huỳnh Phương', 'ACTOR','/assets/images/actors/avatars/Huynh_Phuong.jpeg'),
(64, 'Ngụy Minh Khang', 'DIRECTOR', null),
(65, 'Lý Hùng', 'ACTOR','/assets/images/actors/avatars/Ly_Hung.jpg'),
(66, 'Phương Lan', 'ACTOR','/assets/images/actors/avatars/Phuong_Lan.jpg'),
(67, 'Cát Phượng', 'ACTOR','/assets/images/actors/avatars/Cat_Phuong.jpg'),
(68, 'Kim Tuyến', 'ACTOR','/assets/images/actors/avatars/Kim_Tuyen.jpg'),
(69, 'Elle Fanning', 'ACTOR','/assets/images/actors/avatars/Elle_Fanning.jpg'),
(70, 'Dan Trachtenberg', 'DIRECTOR', null),
(71, 'Dimitrius Schuster-Koloamatangi', 'ACTOR','/assets/images/actors/avatars/Dimitrius_Schuster-Koloamatangi.jpg'),
(72, 'Nadech Kugimiya', 'ACTOR','/assets/images/actors/avatars/Nadech_Kugimiya.jpg'),
(73, 'Narit Yuvaboon', 'DIRECTOR', null),
(74, 'Denise Jelilcha Kapaun', 'ACTOR','/assets/images/actors/avatars/Denise_Jelilcha_Kapaun.jpg'),
(75, 'Mim Rattawadee Wongthong', 'ACTOR','/assets/images/actors/avatars/Mim_Rattawadee_Wongthong.jpg'),
(76, 'Junior Kajbhunditt Jaidee', 'ACTOR','/assets/images/actors/avatars/Junior_Kajbhunditt_Jaidee.jpg'),
(77, 'Friend Peerakrit Phacharaboonyakiat', 'ACTOR','/assets/images/actors/avatars/Friend_Peerakrit_Phacharaboonyakiat.jpg'),
(78, 'Minh Ngọc', 'ACTOR','/assets/images/actors/avatars/Minh_Ngoc.jpg'),
(79, 'Trần Nhân Kiên', 'DIRECTOR', null),
(80, 'Minh Phượng', 'ACTOR','/assets/images/actors/avatars/Minh_Phuong.jpg'),
(81, 'Hồng Thanh', 'ACTOR','/assets/images/actors/avatars/Hong_Thanh.jpg'),
(82, 'Tạ Lâm', 'ACTOR','/assets/images/actors/avatars/Ta_Lam.png'),
(83, 'Ngọc Tưởng', 'ACTOR','/assets/images/actors/avatars/Ngoc_Tuong.jpg'),
(84, 'Quách Ngọc Ngoan', 'ACTOR','/assets/images/actors/avatars/Quach_Ngoc_Ngoan.jpg'),
(85, 'Quốc Công', 'DIRECTOR', null),
(86, 'Xuân Văn', 'ACTOR','/assets/images/actors/avatars/Xuan_Van.jpg'),
(87, 'Nhật Linh', 'ACTOR','/assets/images/actors/avatars/Nhat_Linh.jpg'),
(88, 'Việt Hưng', 'ACTOR','/assets/images/actors/avatars/Viet_Hung.jpg'),
(89, 'Glen Powell', 'ACTOR','/assets/images/actors/avatars/Glen_Powell.jpg'),
(90, 'Edgar Wright', 'DIRECTOR', null),
(91, 'William H. Macy', 'ACTOR','/assets/images/actors/avatars/William_H._Macy.jpg'),
(92, 'Lee Pace', 'ACTOR','/assets/images/actors/avatars/Lee_Pace.jpg'),
(93, 'Emilia Jones', 'ACTOR','/assets/images/actors/avatars/Emilia_Jones.jpg'),
(94, 'Michael Cera', 'ACTOR','/assets/images/actors/avatars/Michael_Cera.jpg'),
(95, 'Liên Bỉnh Phát', 'ACTOR','/assets/images/actors/avatars/Lien_Binh_Phat.jpg'),
(96, 'Kiều Oanh', 'ACTOR','/assets/images/actors/avatars/Kieu_Oanh.jpg'),
(97, 'Lê Hải', 'ACTOR','/assets/images/actors/avatars/Le_Hai.jpg'),
(98, 'Mai Cát Vi', 'ACTOR','/assets/images/actors/avatars/Mai_Cat_Vi.png'),
-- (100, 'Rima Thanh Vy', 'ACTOR','/assets/images/actors/avatars/Rima_Thanh_Vy.jpeg'),
(101, 'Thúy Hạnh', 'ACTOR','/assets/images/actors/avatars/Thuy_Hanh.jpg'),
(102, 'Hoàng Phúc', 'ACTOR','/assets/images/actors/avatars/Hoang_Phuc.jpg'),
(103, 'Kiều Trinh', 'ACTOR','/assets/images/actors/avatars/Kieu_Trinh.jpg'),
(104, 'Tam Triều Dâng', 'ACTOR','/assets/images/actors/avatars/Tam_Trieu_Dang.jpg'),
(105, 'Margot Robbie', 'ACTOR','/assets/images/actors/avatars/Margot_Robbie.jpg'),
(106, 'Jacob Elordi', 'ACTOR','/assets/images/actors/avatars/Jacob_Elordi.jpg'),
(107, 'Hong Chau', 'ACTOR','/assets/images/actors/avatars/Hong_Chau.jpg'),
(108, 'Shazad Latif', 'ACTOR','/assets/images/actors/avatars/Shazad_Latif.jpg'),
(109, 'Alison Oliver', 'ACTOR','/assets/images/actors/avatars/Alison_Oliver.jpg'),
(110, 'Kim Phương', 'ACTOR','/assets/images/actors/avatars/Kim_Phuong.jpeg'),
(111, 'Yada Narilya Gulmongkolpech', 'ACTOR','/assets/images/actors/avatars/Yada_Narilya_Gulmongkolpech.jpg'),
(112, '"Krist" Perawat Sangpotirat', 'ACTOR','/assets/images/actors/avatars/Krist_Perawat_Sangpotirat.jpg'),
(113, 'Choosak Iamsook', 'ACTOR','/assets/images/actors/avatars/Choosak_Iamsook.jpg'),
(114, 'Pongsak Pongsuwan', 'ACTOR','/assets/images/actors/avatars/Pongsak_Pongsuwan.jpg'),
(115, 'Phetthai Vongkumlao', 'ACTOR','/assets/images/actors/avatars/Phetthai_Vongkumlao.png'),
(116, 'Ma Ran Đô', 'ACTOR','/assets/images/actors/avatars/Ma_Ran_Do.jpg'),
(117, 'Nguyên Thảo', 'ACTOR','/assets/images/actors/avatars/Nguyen_Thao.jpg'),
(118, 'Thanh Nam', 'ACTOR','/assets/images/actors/avatars/Thanh_Nam.jpg'),
(119, 'Oscar Dương', 'DIRECTOR', null),
(120, 'Thắng Vũ', 'DIRECTOR', null),
(121, 'Emerald Fennell', 'DIRECTOR', null),
(122, 'Trần Duy Linh', 'DIRECTOR', null),
(123, 'Phạm Trung Hiếu', 'DIRECTOR', null),
(124, ' Choosak Iamsook', 'DIRECTOR', null),
(125, 'Dương Minh Chiến', 'DIRECTOR', null),
(126, 'Kim Hải', 'ACTOR','/assets/images/actors/avatars/Kim_Hai.jpg'),
(127, 'Christine KO', 'DIRECTOR', null),
(128, 'Jung Ryeo-won', 'ACTOR','/assets/images/actors/avatars/Jung_Ryeo-Won.png'),
(129, 'Lee Jung-eun', 'ACTOR','/assets/images/actors/avatars/Lee_Jung-Eun.jpg'),
(130, 'Jang Jin-hee', 'ACTOR','/assets/images/actors/avatars/Jang_Jin-Hee.jpg'),
(131, 'Weeravat Chayochaikon', 'DIRECTOR', null),
(132, 'Ongart Cheamcharoenpornkul', 'DIRECTOR', null),
(133, 'Voravuth Thawinwisitwat', 'DIRECTOR', null),
(134, 'Pae Arak Amornsupasiri', 'ACTOR','/assets/images/actors/avatars/Pae_Arak_Amornsupasiri.jpg'),
(135, 'Foei Patara Eksangkul', 'ACTOR','/assets/images/actors/avatars/Foei_Patara_Eksangkul.jpg'),
(136, 'Kornnaphat Sethratanapong', 'ACTOR','/assets/images/actors/avatars/Kornnaphat_Sethratanapong.png'),
(137, 'Chia-Ying Tsai', 'DIRECTOR', null),
(138, 'Tào Hựu Ninh', 'ACTOR','/assets/images/actors/avatars/Tao_Huu_Ninh.jpg'),
(139, 'Lưu Dĩ Hào', 'ACTOR','/assets/images/actors/avatars/Luu_Di_Hao.jpg'),
(140, 'Viên Lễ Lâm', 'ACTOR','/assets/images/actors/avatars/Vien_Le_Lam.jpg'),
(141, 'Sunghoo Park', 'DIRECTOR', null),
(142, 'Hanazawa Kana', 'ACTOR','/assets/images/actors/avatars/Hanazawa_Kana.jpg'),
(143, 'Nakamura Yuichi', 'ACTOR','/assets/images/actors/avatars/Nakamura_Yuichi.jpg'),
(144, 'Uchiyama Koki', 'ACTOR','/assets/images/actors/avatars/Uchiyama_Koki.png'),
(145, 'Takashi Yamazaki', 'DIRECTOR', null),
(146, 'Ryûnosuke Kamiki', 'ACTOR','/assets/images/actors/avatars/Ryûnosuke_Kamiki.jpg'),
(147, 'Minami Hamabe', 'ACTOR','/assets/images/actors/avatars/Minami_Hamabe.jpg'),
(148, 'Yuki Yamada', 'ACTOR','/assets/images/actors/avatars/Yuki_Yamada.jpg'),
(149, 'Haruo Sotozaki', 'DIRECTOR', null),
(150, 'Natsuki Hanae', 'ACTOR','/assets/images/actors/avatars/Natsuki_Hanae.jpg'),
(151, 'Saori Hayami', 'ACTOR','/assets/images/actors/avatars/Saori_Hayami.jpg'),
(152, 'Yoshitsugu Matsuoka', 'ACTOR','/assets/images/actors/avatars/Yoshitsugu_Matsuoka.jpg'),
(153, 'Shouta Goshozono', 'DIRECTOR', null),
-- (154, 'Yūichi Nakamura', 'ACTOR','/assets/images/actors/avatars/Yūichi_Nakamura.jpg'),
(155, 'Takahiro Sakurai', 'ACTOR','/assets/images/actors/avatars/Takahiro_Sakurai.jpg'),
(156, 'Aya Endō', 'ACTOR','/assets/images/actors/avatars/Aya_Endō.jpg'),
(157, 'Anna Nagase', 'ACTOR','/assets/images/actors/avatars/Anna_Nagase.png'),
(158, 'Takehito Koyasu', 'ACTOR','/assets/images/actors/avatars/Takehito_Koyasu.jpg'),
(159, 'Michiko Kaiden', 'ACTOR','/assets/images/actors/avatars/Michiko_Kaiden.jpg'),
(160, 'Lee Eung-bok', 'DIRECTOR', null),
(161, 'Park So-hyun', 'DIRECTOR', null),
(162, 'Kim Yoo Jung', 'ACTOR','/assets/images/actors/avatars/Kim_Yoo_Jung.jpg'),
(163, 'Kim Young Dae', 'ACTOR','/assets/images/actors/avatars/Kim_Young_Dae.jpg'),
(164, 'Kim Do Hoon', 'ACTOR','/assets/images/actors/avatars/Kim_Do_Hoon.jpg'),
(165, 'Taweewat Wantha', 'DIRECTOR', null),
(166, 'Phiravich Attachitsataporn', 'ACTOR','/assets/images/actors/avatars/Phiravich_Attachitsataporn.jpg'),
(167, 'Nichaphat Chatchaipholrat', 'ACTOR','/assets/images/actors/avatars/Nichaphat_Chatchaipholrat.jpg'),
(168, 'Jirayu Tangsrisuk', 'ACTOR','/assets/images/actors/avatars/Jirayu_Tangsrisuk.jpg'),
(169, 'Shinkai Makoto', 'DIRECTOR', null),
(170, 'Mizuhashi Kenji', 'ACTOR','/assets/images/actors/avatars/Mizuhashi_Kenji.jpg'),
(171, 'Kondou Yoshimi', 'ACTOR','/assets/images/actors/avatars/Kondou_Yoshimi.jpg'),
(172, 'Thu Trang', 'DIRECTOR', null),
(369, 'Thu Trang', 'ACTOR','/assets/images/actors/avatars/Thu_Trang.jpg'),
(173, 'Trâm Anh', 'ACTOR','/assets/images/actors/avatars/Tram_Anh.jpg'),
(174, 'Võ Điền Gia Huy', 'ACTOR','/assets/images/actors/avatars/Vo_Dien_Gia_Huy.jpg'),
(175, 'Khả Như', 'ACTOR','/assets/images/actors/avatars/Kha_Nhu.jpeg'),
(176, 'La Thành', 'ACTOR','/assets/images/actors/avatars/La_Thanh.jpg'),
(177, 'Trương Minh Thảo', 'ACTOR','/assets/images/actors/avatars/Truong_Minh_Thao.jpg'),
(178, 'Nam Dae Jung', 'DIRECTOR', null),
(179, 'Kang Ha Neul', 'ACTOR','/assets/images/actors/avatars/Kang_Ha_Neul.jpg'),
(180, 'Cha Eun Woo', 'ACTOR','/assets/images/actors/avatars/Cha_Eun_Woo.jpg'),
(181, 'Kim Young Kwang', 'ACTOR','/assets/images/actors/avatars/Kim_Young_Kwang.jpg'),
(182, 'Kang Young Suk', 'ACTOR','/assets/images/actors/avatars/Kang_Young_Suk.jpg'),
(183, 'Han Seon Hwa', 'ACTOR','/assets/images/actors/avatars/Han_Seon_Hwa.jpg'),
(184, 'Lê Thanh Sơn', 'DIRECTOR', null),
(185, 'NSND Kim Xuân', 'ACTOR','/assets/images/actors/avatars/NSND_Kim_Xuân.jpg'),
(186, 'Tuấn Trần', 'ACTOR','/assets/images/actors/avatars/Tuan_Tran.jpg'),
(187, 'Phương Anh Đào', 'ACTOR','/assets/images/actors/avatars/Phuong_Anh_Dao.jpg'),
(188, 'Võ Tấn Phát', 'ACTOR','/assets/images/actors/avatars/Vo_Tan_Phat.jpeg'),
(189, 'Hưng Nguyễn', 'ACTOR','/assets/images/actors/avatars/Hung_Nguyen.jpg'),
(190, 'Trung Dân', 'ACTOR','/assets/images/actors/avatars/Trung_Dan.jpg'),
(191, 'Khương Lê', 'ACTOR','/assets/images/actors/avatars/Khuong_Le.jpg'),
(192, 'Chị Phiến', 'ACTOR','/assets/images/actors/avatars/Chi_Phien.jpg'),
(193, 'Thư Đan', 'ACTOR','/assets/images/actors/avatars/Thu_Dan.jpg'),
(194, 'Alessandro Carloni', 'DIRECTOR', null),
(195, 'Erica Rivinoja', 'DIRECTOR', null),
(196, 'Bill Hader', 'ACTOR','/assets/images/actors/avatars/Bill_Hader.jpg'),
(197, 'Xochitl Gomez', 'ACTOR','/assets/images/actors/avatars/Xochitl_Gomez.jpg'),
(198, 'Matt Berry', 'ACTOR','/assets/images/actors/avatars/Matt_Berry.jpg'),
(199, 'Paula Pell', 'ACTOR','/assets/images/actors/avatars/Paula_Pell.jpg'),
(200, 'Maggie Gyllenhaal', 'DIRECTOR', null),
(201, 'Jake Gyllenhaal', 'ACTOR','/assets/images/actors/avatars/Jake_Gyllenhaal.jpg'),
(202, 'Christian Bale', 'ACTOR','/assets/images/actors/avatars/Christian_Bale.jpg'),
(203, 'Jessie Buckley', 'ACTOR','/assets/images/actors/avatars/Jessie_Buckley.jpg'),
(204, 'Paul Feig', 'DIRECTOR', null),
(205, 'Sydney Sweeney', 'ACTOR','/assets/images/actors/avatars/Sydney_Sweeney.jpg'),
(206, 'Brandon Sklenar', 'ACTOR','/assets/images/actors/avatars/Brandon_Sklenar.jpg'),
(207, 'Amanda Seyfried', 'ACTOR','/assets/images/actors/avatars/Amanda_Seyfried.jpg'),
(208, 'Katsuya Shigehara', 'DIRECTOR', null),
(209, 'Minami Takayama', 'ACTOR','/assets/images/actors/avatars/Minami_Takayama.jpg'),
(210, 'Wakana Yamazaki', 'ACTOR','/assets/images/actors/avatars/Wakana_Yamazaki.jpg'),
(211, 'Rikiya Koyama', 'ACTOR','/assets/images/actors/avatars/Rikiya_Koyama.jpg'),
(212, 'Megumi Hayashibara', 'ACTOR','/assets/images/actors/avatars/Megumi_Hayashibara.jpg'),
(213, 'Daniel Chong', 'DIRECTOR', null),
(214, 'Jon Hamm', 'ACTOR','/assets/images/actors/avatars/Jon_Hamm.jpg'),
(215, 'Bobby Moynihan', 'ACTOR','/assets/images/actors/avatars/Bobby_Moynihan.jpg'),
(216, 'Piper Curda', 'ACTOR','/assets/images/actors/avatars/Piper_Curda.jpg'),
(217, 'Josh Boone', 'DIRECTOR', null),
(218, 'Allison Williams', 'ACTOR','/assets/images/actors/avatars/Allison_Williams.jpg'),
(219, 'Dave Franco', 'ACTOR','/assets/images/actors/avatars/Dave_Franco.jpg'),
(220, 'Nguyễn Ngọc Lâm', 'DIRECTOR', null),
(221, 'NSƯT Hữu Châu', 'ACTOR','/assets/images/actors/avatars/Huu_Chau.jpg'),
(222, 'NSND Hồng Vân', 'ACTOR','/assets/images/actors/avatars/NSND_Hồng_Vân.jpg'),
(223, 'Thúy Diễm', 'ACTOR','/assets/images/actors/avatars/Thuy_Diem.jpg'),
(224, 'Đình Khang', 'ACTOR','/assets/images/actors/avatars/Đinh_Khang.jpg'),
(225, 'Leona Khánh Tiên', 'ACTOR','/assets/images/actors/avatars/Leona_Khanh_Tien.jpg'),
(226, 'Trọng Phương', 'ACTOR','/assets/images/actors/avatars/Trong_Phuong.jpg'),
(227, 'Thiên Ân', 'ACTOR','/assets/images/actors/avatars/Thien_An.jpg'),
(228, 'Sam Raimi', 'DIRECTOR', null),
(229, 'Dylan O''Brien', 'ACTOR','/assets/images/actors/avatars/Dylan_O''Brien.jpg'),
(230, 'Rachel McAdams', 'ACTOR','/assets/images/actors/avatars/Rachel_McAdams.jpg'),
(231, 'Dennis Haysbert', 'ACTOR','/assets/images/actors/avatars/Dennis_Haysbert.jpg'),
(232, 'Kim Hee Sung', 'DIRECTOR', null),
(233, 'Ji Seung Hyun', 'ACTOR','/assets/images/actors/avatars/Ji_Seung_Hyun.jpeg'),
(234, 'Jung Hye Seong', 'ACTOR','/assets/images/actors/avatars/Jung_Hye_Seong.jpg'),
(235, 'Osgood Perkins', 'DIRECTOR', null),
(236, 'Tatiana Maslany', 'ACTOR','/assets/images/actors/avatars/Tatiana_Maslany.jpg'),
(237, 'Rossif Sutherland', 'ACTOR','/assets/images/actors/avatars/Rossif_Sutherland.jpg'),
(238, 'Claire Friesen', 'ACTOR','/assets/images/actors/avatars/Claire_Friesen.jpg'),
(239, 'Johannes Roberts', 'DIRECTOR', null),
(240, 'Johnny Sequoyah', 'ACTOR','/assets/images/actors/avatars/Johnny_Sequoyah.jpg'),
(241, 'Troy Kotsur', 'ACTOR','/assets/images/actors/avatars/Troy_Kotsur.jpg'),
(242, 'Jessica Alexander', 'ACTOR','/assets/images/actors/avatars/Jessica_Alexander.jpg'),
(243, 'Takahata Isao', 'DIRECTOR', null),
(244, 'Tatsumi Tsutomu', 'ACTOR','/assets/images/actors/avatars/Tatsumi_Tsutomu.jpg'),
(245, 'Shiraishi Ayano', 'ACTOR','/assets/images/actors/avatars/Shiraishi_Ayano.jpg'),
(246, 'Shinohara Yoshiko', 'ACTOR','/assets/images/actors/avatars/Shinohara_Yoshiko.jpg'),
(247, 'Simon McQuoid', 'DIRECTOR', null),
(248, 'Karl Urban', 'ACTOR','/assets/images/actors/avatars/Karl_Urban.jpeg'),
(249, 'Adeline Rudolph', 'ACTOR','/assets/images/actors/avatars/Adeline_Rudolph.jpg'),
(250, 'Jessica McNamee', 'ACTOR','/assets/images/actors/avatars/Jessica_McNamee.jpg'),
(251, 'Josh Lawson', 'ACTOR','/assets/images/actors/avatars/Josh_Lawson.jpg'),
(252, 'Ludi Lin', 'ACTOR','/assets/images/actors/avatars/Ludi_Lin.jpg'),
(253, 'Mehcad Brooks', 'ACTOR','/assets/images/actors/avatars/Mehcad_Brooks.jpg'),
(254, 'Tati Gabrielle', 'ACTOR','/assets/images/actors/avatars/Tati_Gabrielle.jpg'),
(255, 'Lewis Tan', 'ACTOR','/assets/images/actors/avatars/Lewis_Tan.jpg'),
(256, 'Kim Hyeon-joon', 'DIRECTOR', null),
(257, 'Kim Byung-Choon', 'ACTOR','/assets/images/actors/avatars/Kim_Byung-Choon.jpg'),
(258, 'Chanmi', 'ACTOR','/assets/images/actors/avatars/Chanmi.png'),
(259, 'Seo Dong-won', 'ACTOR','/assets/images/actors/avatars/Seo_Dong-won.jpg'),
(260, 'Lê Nhật Quang (Leon Le)', 'DIRECTOR', null),
(261, 'Đỗ Thị Hải Yến', 'ACTOR','/assets/images/actors/avatars/Đo_Thi_Hai_Yen.jpg'),
(262, 'Trần Thế Mạnh', 'ACTOR','/assets/images/actors/avatars/Tran_The_Manh.jpg'),
(263, 'Ngô Hồng Ngọc', 'ACTOR','/assets/images/actors/avatars/Ngo_Hong_Ngoc.jpg'),
(264, 'Lý Kiều Hạnh', 'ACTOR','/assets/images/actors/avatars/Ly_Kieu_Hanh.jpg'),
(265, 'Lê Văn Thân', 'ACTOR','/assets/images/actors/avatars/Le_van_Than.jpg'),
(266, 'Mamoru Hosoda', 'DIRECTOR', null),
(267, 'Mana Ashida', 'ACTOR','/assets/images/actors/avatars/Mana_Ashida.jpg'),
(268, 'Masaki Okada', 'ACTOR','/assets/images/actors/avatars/Masaki_Okada.jpg'),
(269, 'Kôji Yakusho', 'ACTOR','/assets/images/actors/avatars/Kôji_Yakusho.jpeg'),
(270, 'Masakazu Hashimoto', 'DIRECTOR', null),
(271, 'Yumiko Kobayashi', 'ACTOR','/assets/images/actors/avatars/Yumiko_Kobayashi.jpg'),
(272, 'Miki Narahashi', 'ACTOR','/assets/images/actors/avatars/Miki_Narahashi.jpg'),
(273, 'Toshiyuki Morikawa', 'ACTOR','/assets/images/actors/avatars/Toshiyuki_Morikawa.jpg'),
(274, 'Satomi Kōrogi', 'ACTOR','/assets/images/actors/avatars/Satomi_Kōrogi.jpeg'),
(275, 'Derek Drymon', 'DIRECTOR', null),
(276, 'Tom Kenny', 'ACTOR','/assets/images/actors/avatars/Tom_Kenny.jpg'),
(277, 'Clancy Brown', 'ACTOR','/assets/images/actors/avatars/Clancy_Brown.jpg'),
(278, 'Rodger Bumpass', 'ACTOR','/assets/images/actors/avatars/Rodger_Bumpass.png'),
(279, 'Bill Fagerbakke', 'ACTOR','/assets/images/actors/avatars/Bill_Fagerbakke.jpg'),
(280, 'Carolyn Lawrence', 'ACTOR','/assets/images/actors/avatars/Carolyn_Lawrence.jpg'),
(281, 'Mr. Lawrence', 'ACTOR','/assets/images/actors/avatars/Mr._Lawrence.jpg'),
(282, 'George Lopez', 'ACTOR','/assets/images/actors/avatars/George_Lopez.jpg'),
(283, 'Isis “Ice Spice” Gaston', 'ACTOR','/assets/images/actors/avatars/Isis_“Ice Spice”_Gaston.jpg'),
(284, 'Arturo Castro', 'ACTOR','/assets/images/actors/avatars/Arturo_Castro.jpg'),
(285, 'Sherry Cola', 'ACTOR','/assets/images/actors/avatars/Sherry_Cola.jpg'),
(286, 'Regina Hall', 'ACTOR','/assets/images/actors/avatars/Regina_Hall.jpg'),
(287, 'Mark Hamill', 'ACTOR','/assets/images/actors/avatars/Mark_Hamill.jpg'),
(288, 'Nian Wels', 'DIRECTOR', null),
(289, 'Hoàng Nam', 'DIRECTOR', null),
(290, 'Trần Tú', 'ACTOR','/assets/images/actors/avatars/Tran_Tu.jpg'),
(291, 'NSND Thanh Hoa', 'ACTOR','/assets/images/actors/avatars/NSND_Thanh_Hoa.jpg'),
(292, 'NSND Trần Lực', 'ACTOR','/assets/images/actors/avatars/NSND_Tran_Luc.jpg'),
(293, 'NSND Bùi Bài Bình', 'ACTOR','/assets/images/actors/avatars/NSND_Bui_Bai_Binh.jpg'),
(294, 'NSƯT Chiều Xuân', 'ACTOR','/assets/images/actors/avatars/NSƯT_Chieu_Xuan.jpg'),
(295, 'Quách Thu Phương', 'ACTOR','/assets/images/actors/avatars/Quach_Thu_Phuong.png'),
(296, 'Hà Hương', 'ACTOR','/assets/images/actors/avatars/Ha_Huong.jpg'),
(297, 'Tuấn Hưng', 'ACTOR','/assets/images/actors/avatars/Tuan_Hung.jpg'),
(298, 'Nàng Mơ', 'ACTOR','/assets/images/actors/avatars/Nang_Mo.jpg'),
(299, 'Christopher Nolan', 'DIRECTOR', null),
(300, 'Benny Safdie', 'ACTOR','/assets/images/actors/avatars/Benny_Safdie.jpg'),
(301, 'Anne Hathaway', 'ACTOR','/assets/images/actors/avatars/Anne_Hathaway.jpg'),
(302, 'Matt Damon', 'ACTOR','/assets/images/actors/avatars/Matt_Damon.jpg'),
(303, 'Robert Pattinson', 'ACTOR','/assets/images/actors/avatars/Robert_Pattinson.jpg'),
(304, 'Tom Holland', 'ACTOR','/assets/images/actors/avatars/Tom_Holland.jpg'),
(305, 'Zendaya', 'ACTOR','/assets/images/actors/avatars/Zendaya.jpg'),
(306, 'Charlize Theron', 'ACTOR','/assets/images/actors/avatars/Charlize_Theron.jpg'),
(307, 'Phil Lord', 'DIRECTOR', null),
(308, 'Christopher Miller', 'DIRECTOR', null),
(309, 'Ryan Gosling', 'ACTOR','/assets/images/actors/avatars/Ryan_Gosling.jpg'),
(310, 'Liz Kingsman', 'ACTOR','/assets/images/actors/avatars/Liz_Kingsman.jpg'),
(311, 'Milana Vayntrub', 'ACTOR','/assets/images/actors/avatars/Milana_Vayntrub.jpg'),
(312, 'Sandra Hüller', 'ACTOR','/assets/images/actors/avatars/Sandra_Hüller.jpg'),
(313, 'Jon M. Chu', 'DIRECTOR', null),
(314, 'Cynthia Erivo', 'ACTOR','/assets/images/actors/avatars/Cynthia_Erivo.jpg'),
(315, 'Ariana Grande', 'ACTOR','/assets/images/actors/avatars/Ariana_Grande.webp'),
(316, 'Jonathan Bailey', 'ACTOR','/assets/images/actors/avatars/Jonathan_Bailey.jpg'),
(317, 'Ethan Slater', 'ACTOR','/assets/images/actors/avatars/Ethan_Slater.jpeg'),
(318, 'Bowen Yang', 'ACTOR','/assets/images/actors/avatars/Bowen_Yang.jpg'),
(319, 'Marissa Bode', 'ACTOR','/assets/images/actors/avatars/Marissa_Bode.jpg'),
(320, 'Michelle Yeoh', 'ACTOR','/assets/images/actors/avatars/Michelle_Yeoh.jpg'),
(321, 'Jeff Goldblum', 'ACTOR','/assets/images/actors/avatars/Jeff_Goldblum.jpg'),
(322, 'Tomy Dewo', 'DIRECTOR', null),
(323, 'Satine Zaneta', 'ACTOR','/assets/images/actors/avatars/Satine_Zaneta.jpg'),
(324, 'Niken Anjani', 'ACTOR','/assets/images/actors/avatars/Niken_Anjani.jpg'),
(325, 'Park Jun-soo', 'DIRECTOR', null),
(326, 'J-hope', 'ACTOR','/assets/images/actors/avatars/J-hope.jpg'),
(327, 'Jin', 'ACTOR','/assets/images/actors/avatars/Jin.jpg'),
(328, 'Jungkook', 'ACTOR','/assets/images/actors/avatars/Jungkook.jpg'),
(329, 'Crush', 'ACTOR','/assets/images/actors/avatars/Crush.jpg'),
(330, 'Becky G', 'ACTOR','/assets/images/actors/avatars/Becky_G.jpg'),
(331, 'Miguel', 'ACTOR','/assets/images/actors/avatars/Miguel.jpg'),
(332, 'Ruben Fleischer', 'DIRECTOR', null),
(333, 'Jesse Eisenberg', 'ACTOR','/assets/images/actors/avatars/Jesse_Eisenberg.jpg'),
(334, 'Woody Harrelson', 'ACTOR','/assets/images/actors/avatars/Woody_Harrelson.jpg'),
(335, 'Isla Fisher', 'ACTOR','/assets/images/actors/avatars/Isla_Fisher.jpg'),
(336, 'Justice Smith', 'ACTOR','/assets/images/actors/avatars/Justice_Smith.jpg'),
(337, 'Dominic Sessa', 'ACTOR','/assets/images/actors/avatars/Dominic_Sessa.jpg'),
(338, 'Rosamund Pike', 'ACTOR','/assets/images/actors/avatars/Rosamund_Pike.jpg'),
(339, 'Ariana Greenblatt', 'ACTOR','/assets/images/actors/avatars/Ariana_Greenblatt.jpg'),
(340, 'Hong Won-ki', 'DIRECTOR', null),
(341, 'Yoo Jae-myung', 'ACTOR','/assets/images/actors/avatars/Yoo_Jae-myung.jpg'),
(342, 'Moon Chae-won', 'ACTOR','/assets/images/actors/avatars/Moon_Chae-won.jpg'),
(343, 'Seo Young-hee', 'ACTOR','/assets/images/actors/avatars/Seo_Young-hee.jpeg'),
(344, 'Won Hyun-joon', 'ACTOR','/assets/images/actors/avatars/Won_Hyun-joon.jpg'),
(345, 'Ngọc Xuân', 'ACTOR','/assets/images/actors/avatars/Ngoc_Xuan.jpg'),
(346, 'Emma Le', 'ACTOR','/assets/images/actors/avatars/Emma_Le.png'),
(347, 'Hứa Vĩ Văn', 'ACTOR','/assets/images/actors/avatars/Hua_Vi_Van.jpg'),
(348, 'Đinh Y Nhung', 'ACTOR','/assets/images/actors/avatars/Đinh_Y_Nhung.jpg'),
(349, 'Kenji Iwaisawa', 'DIRECTOR', null),
(350, 'Tori Matsuzaka', 'ACTOR','/assets/images/actors/avatars/Tori_Matsuzaka.jpg'),
(351, 'Shota Sometani', 'ACTOR','/assets/images/actors/avatars/Shota_Sometani.jpg'),
(352, 'Rie Takahashi', 'ACTOR','/assets/images/actors/avatars/Rie_Takahashi.jpg'),
(353, 'Hồng Tử Huyên', 'DIRECTOR', null),
(354, 'Lâm Bách Hoành', 'ACTOR','/assets/images/actors/avatars/Lam_Bach_Hoanh.jpg'),
(355, 'Tống Vân Hoa', 'ACTOR','/assets/images/actors/avatars/Tong_Van_Hoa.jpg'),
(356, 'Vương Bá Kiệt', 'ACTOR','/assets/images/actors/avatars/Vuong_Ba_Kiet.jpg'),
(357, 'Lý Lý Nhân', 'ACTOR','/assets/images/actors/avatars/Ly_Ly_Nhan.jpg'),
(358, 'Diêu Dĩ Đề', 'ACTOR','/assets/images/actors/avatars/Dieu_Di_De.jpg'),
(359, 'Thái Phàm Hi', 'ACTOR','/assets/images/actors/avatars/Thai_Pham_Hi.jpg'),
(360, 'Seong-ho Jang', 'DIRECTOR', null),
(361, 'Pierce Brosnan', 'ACTOR','/assets/images/actors/avatars/Pierce_Brosnan.jpg'),
(362, 'Roman Griffin Davis', 'ACTOR','/assets/images/actors/avatars/Roman_Griffin_Davis.jpg'),
(363, 'AmazeVR', 'DIRECTOR', null),
(364, 'Yeonjun', 'ACTOR','/assets/images/actors/avatars/Yeonjun.jpg'),
(365, 'Choi Soo-bin', 'ACTOR','/assets/images/actors/avatars/Choi_Soo-bin.jpg'),
(366, 'Beomgyu', 'ACTOR','/assets/images/actors/avatars/Beomgyu.jpg'),
(367, 'Huening Kai', 'ACTOR','/assets/images/actors/avatars/Huening_Kai.jpg'),
(368, 'Taehyun', 'ACTOR','/assets/images/actors/avatars/Taehyun.jpg'),
-- Movie 69
(370, 'Henrik Martin Dahlsbakken', 'DIRECTOR', null),
(371, 'Vivild Falk Berg', 'ACTOR', '/assets/images/actors/avatars/Vivild_Falk_Berg.jpg'),
(372, 'Vegard Strand Eide', 'ACTOR', '/assets/images/actors/avatars/Vegard_Strand_Eide.jpg'),
(373, 'Charlotte Frogner', 'ACTOR', '/assets/images/actors/avatars/Charlotte_Frogner.webp'),

-- Movie 70
(374, 'Nam Đoàn', 'DIRECTOR', null),
(375, 'Hậu Nguyễn', 'DIRECTOR', null),
(376, 'Hoàng Khuyết', 'ACTOR', '/assets/images/actors/avatars/Hoang_Khuyet.jpg'),
(377, 'Thùy Tiên', 'ACTOR', '/assets/images/actors/avatars/Thuy_Tien.jpg'),
(378, 'Trần Vũ', 'ACTOR', '/assets/images/actors/avatars/Tran_Vu.jpg'),

-- Movie 71
(379, 'Yaguchi Shinobu', 'DIRECTOR', null),
(380, 'Kôji Seto', 'ACTOR', '/assets/images/actors/avatars/Koji_Seto.jpg'),
(381, 'Tetsushi Tanaka', 'ACTOR', '/assets/images/actors/avatars/Tetsushi_Tanaka.jpg'),
(382, 'Ken Yasuda', 'ACTOR', '/assets/images/actors/avatars/Ken_Yasuda.jpg'),
(383, 'Jun Fubuki', 'ACTOR', '/assets/images/actors/avatars/Jun_Fubuki.webp'),

-- Movie 72 & 80 (Miyazaki Hayao dùng chung ID 384)
(384, 'Miyazaki Hayao', 'DIRECTOR', null),
(385, 'Hitoshi Takagi', 'ACTOR', '/assets/images/actors/avatars/Hitoshi_Takagi.jpg'),
(386, 'Noriko Hidaka', 'ACTOR', '/assets/images/actors/avatars/Noriko_Hidaka.webp'),
(387, 'Chika Sakamoto', 'ACTOR', '/assets/images/actors/avatars/Chika_Sakamoto.webp'),

-- Movie 73
(388, 'Tom Gormican', 'DIRECTOR', null),
(389, 'Jack Black', 'ACTOR', '/assets/images/actors/avatars/Jack_Black.jpg'),
(390, 'Paul Rudd', 'ACTOR', '/assets/images/actors/avatars/Paul_Rudd.jpg'),
(391, 'Steve Zahn', 'ACTOR', '/assets/images/actors/avatars/Steve_Zahn.jpg'),
(392, 'Thandiwe Newton', 'ACTOR', '/assets/images/actors/avatars/Thandiwe_Newton.png'),
(393, 'Daniela Melchior', 'ACTOR', '/assets/images/actors/avatars/Daniela_Melchior.jpg'),
(394, 'Selton Mello', 'ACTOR', '/assets/images/actors/avatars/Selton_Mello.jpg'),

-- Movie 74
(395, 'Azhar Lubis Kinois', 'DIRECTOR', null),
(396, 'Arifin Putra', 'ACTOR', '/assets/images/actors/avatars/Arifin_Putra.jpg'),
(397, 'Nayla D. Purnama', 'ACTOR', '/assets/images/actors/avatars/Nayla_D._Purnama.jpg'),

-- Movie 75
(398, 'HONG KI-WON', 'DIRECTOR', null),
(399, 'LEE JAE-IN', 'ACTOR', '/assets/images/actors/avatars/LEE_JAE-IN.png'),
(400, 'HONG KYUNG', 'ACTOR', '/assets/images/actors/avatars/HONG_KYUNG.jpg'),
(401, 'JUNG MAN-SI', 'ACTOR', '/assets/images/actors/avatars/JUNG_MAN-SI.jpg'),
(402, 'YU SU-BIN', 'ACTOR', '/assets/images/actors/avatars/YU_SU-BIN.webp'),
(403, 'KIM KUK-HEE', 'ACTOR', '/assets/images/actors/avatars/KIM_KUK-HEE.jpg'),
(404, 'CHOI JUNG-UN', 'ACTOR', '/assets/images/actors/avatars/CHOI_JUNG-UN.jpg'),

-- Movie 76
(405, 'Ding Zhong', 'DIRECTOR', null),
(406, 'Xin Li', 'ACTOR', '/assets/images/actors/avatars/Xin_Li.jpg'),
(407, 'Xiaoyu Liu', 'ACTOR', '/assets/images/actors/avatars/Xiaoyu_Liu.webp'),
(408, 'Tom Fu', 'ACTOR', '/assets/images/actors/avatars/Tom_Fu.jpg'),

-- Movie 77
(409, 'Yonebayashi Hiromasa', 'DIRECTOR', null),
(410, 'Mirai Shida', 'ACTOR', '/assets/images/actors/avatars/Mirai_Shida.jpg'),
(411, 'Ryunosuke Kamiki', 'ACTOR', '/assets/images/actors/avatars/Ryunosuke_Kamiki.jpg'),
(412, 'Tatsuya Fujiwara', 'ACTOR', '/assets/images/actors/avatars/Tatsuya_Fujiwara.jpg'),

-- Movie 78
(413, 'Junya Enoki', 'ACTOR', '/assets/images/actors/avatars/Junya_Enoki.jpg'),
(414, 'Yuma Uchida', 'ACTOR', '/assets/images/actors/avatars/Yuma_Uchida.jpg'),
(415, 'Asami Seto', 'ACTOR', '/assets/images/actors/avatars/Asami_Seto.jpg'),
(416, 'Yuichi Nakamura', 'ACTOR', '/assets/images/actors/avatars/Yuichi_Nakamura.jpg'),

-- Movie 79
(417, 'Tatsuya Yoshihara', 'DIRECTOR', null),
(418, 'Kikunosuke Toya', 'ACTOR', '/assets/images/actors/avatars/Kikunosuke_Toya.jpg'),
(419, 'Tomori Kusunoki', 'ACTOR', '/assets/images/actors/avatars/Tomori_Kusunoki.jpg'),
(420, 'Shôgo Sakata', 'ACTOR', '/assets/images/actors/avatars/Shogo_Sakata.webp'),

-- Movie 80 (Đạo diễn ID 384 đã có ở trên)
(421, 'Yasuo Yamada', 'ACTOR', '/assets/images/actors/avatars/Yasuo_Yamada.webp'),
(422, 'Eiko Masuyama', 'ACTOR', '/assets/images/actors/avatars/Eiko_Masuyama.jpg'),
(423, 'Kiyoshi Kobayashi', 'ACTOR', '/assets/images/actors/avatars/Kiyoshi_Kobayashi.jpg'),

-- Movie 81 (Quang Tuấn-46, Quách Ngọc Ngoan-84, Bích Ngọc-26 đã có)
(424, 'Hoàng Tuấn Cường', 'DIRECTOR', null),
(425, 'Hoài Lâm', 'ACTOR', '/assets/images/actors/avatars/Hoai_Lam.jpg'),
(426, 'Sỹ Toàn', 'ACTOR', '/assets/images/actors/avatars/Sy_Toan.jpg'),
(427, 'Thanh Hương', 'ACTOR', '/assets/images/actors/avatars/Thanh_Huong.jpg'),
(428, 'Lê Minh Thuấn', 'ACTOR', '/assets/images/actors/avatars/Le_Minh_Thuan.jpg'),
(429, 'NSƯT Hạnh Thuý', 'ACTOR', '/assets/images/actors/avatars/NSUT_Hanh_Thuy.webp'),
(430, 'Hoàng Yến', 'ACTOR', '/assets/images/actors/avatars/Hoang_Yen.jpg'),
(431, 'Lâm Thanh Sơn', 'ACTOR', '/assets/images/actors/avatars/Lam_Thanh_Son.jpg'),
(432, 'Đình Hiếu', 'ACTOR', '/assets/images/actors/avatars/Dinh_Hieu.webp'),
(433, 'Hoàng Trinh', 'ACTOR', '/assets/images/actors/avatars/Hoang_Trinh.webp'),

-- Movie 82
(434, 'Gang Zhang', 'DIRECTOR', null),
(435, 'Eric Bauza', 'ACTOR', '/assets/images/actors/avatars/Eric_Bauza.jpg'),
(436, 'Ben Diskin', 'ACTOR', '/assets/images/actors/avatars/Ben_Diskin.jpg'),
(437, 'Janice Kawaye', 'ACTOR', '/assets/images/actors/avatars/Janice_Kawaye.jpg'),

-- Movie 83
(438, 'Dyan Sunu Prastowo', 'DIRECTOR', null),
(439, 'Nirina Zubir', 'ACTOR', '/assets/images/actors/avatars/Nirina_Zubir.webp'),
(440, 'Nugie', 'ACTOR', '/assets/images/actors/avatars/Nugie.jpg'),
(441, 'Mutia Datau', 'ACTOR', '/assets/images/actors/avatars/Mutia_Datau.jpg');

DELETE FROM movie_cast;

INSERT INTO movie_cast (movie_id, cast_id) VALUES
(1, 72),(1, 73),(1, 74),(1, 75),(1, 76),(1, 77),
(2, 1),(2, 2),(2, 3),(2, 4),(2, 5),(2, 6),
(3, 46),(3, 47),(3, 48),(3, 49),(3, 50),(3, 51),
(4, 4),(4, 52),(4, 53),(4, 54),(4, 55),(4, 56),(4, 57),
(5, 12),(5, 101),(5, 102),(5, 103),(5, 126),(5, 120),
(6, 17),(6, 18),(6, 19),(6, 20),(6, 21),
(7, 22),(7, 23),(7, 24), (7, 25),(7, 26),
(8, 27),(8, 28),(8, 29), (8, 30),(8, 32),
(9, 84),(9, 85),(9, 86),(9, 87),(9, 88),
(10, 111),(10, 112),(10, 113),(10, 114),(10, 115),(10, 124),
(11, 78),(11, 79),(11, 80),(11, 81), (11, 82),
(12, 69),(12, 70),(12, 71),
(13, 38),(13, 39),(13, 40),(13, 41),
(14, 89),(14, 90),(14, 91),(14, 92),(14, 93),(14, 94),
(15, 46),(15, 116),(15, 117),(15, 118),(15, 125),
(16, 33),(16, 34),(16, 35),(16, 36),(16, 37),
(17, 95),(17, 104),(17, 96),(17, 97),(17, 98),(17, 119),
(18, 58),(18, 59),(18, 60),(18, 61),(18, 62),
(19, 63),(19, 64),(19, 65),(19, 66),(19, 67),(19, 68),
(20, 7),(20, 8),(20, 9),(20, 10),(20, 11),(20, 12),
(21, 42),(21, 43),(21, 44),(21, 45),
(22, 126),(22, 82),(22, 110), (22, 122),(22, 123),
(23, 13),(23, 14),(23, 15),(23, 16),
(24, 105),(24, 106),(24, 107),(24, 108),(24, 109),(24, 121),
(25, 127),(25, 128),(25, 129),(25, 130),
(26, 131),(26, 132),(26, 133),(26, 134),(26, 135),(26, 136),
(27, 137),(27, 138),(27, 139),(27, 140),
(28, 141),(28, 142),(28, 143),(28, 144),
(29, 145),(29, 146),(29, 147),(29, 148),
(30, 149),(30, 150),(30, 151),(30, 152),
(31, 153),(31, 143),(31, 155),(31, 156),(31, 157),(31, 158),(31, 159),
(32, 160),(32, 161),(32, 162),(32, 163),(32, 164),
(33, 165), (33, 166), (33, 167), (33, 168),
(34, 169), (34, 170), (34, 171),
(35, 172), (35, 173), (35, 174), (35, 175), (35, 176), (35, 177), (35, 369),
(36, 178), (36, 179), (36, 180), (36, 181), (36, 182), (36, 183),
(37, 184), (37, 185), (37, 186), (37, 187), (37, 188), (37, 189), (37, 176), (37, 190), (37, 191), (37, 82), (37, 84), (37, 192), (37, 193),
(38, 194), (38, 195), (38, 196), (38, 197), (38, 198), (38, 60), (38, 199),
(39, 200), (39, 201), (39, 202), (39, 203),
(40, 204), (40, 205), (40, 206), (40, 207),
(41, 208), (41, 209), (41, 210), (41, 211), (41, 212),
(42, 213), (42, 214), (42, 215), (42, 216),
(43, 217), (43, 218), (43, 42), (43, 219),
(44, 220), (44, 221), (44, 222), (44, 177), (44, 223), (44, 224), (44, 126), (44, 225), (44, 226), (44, 227),
(45, 228), (45, 229), (45, 230), (45, 231),
(46, 232), (46, 233), (46, 234),
(47, 235), (47, 236), (47, 237), (47, 238),
(48, 239), (48, 240), (48, 241), (48, 242),
(49, 243), (49, 244), (49, 245), (49, 246),
(50, 247), (50, 248), (50, 249), (50, 250), (50, 251), (50, 252), (50, 253), (50, 254), (50, 255),
(51, 256), (51, 257), (51, 258), (51, 259),
(52, 260), (52, 95), (52, 261), (52, 262), (52, 263), (52, 264), (52, 265),
(53, 266), (53, 267), (53, 268), (53, 269),
(54, 270), (54, 271), (54, 272), (54, 273), (54, 274),
(55, 275), (55, 276), (55, 277), (55, 278), (55, 279), (55, 280), (55, 281), (55, 282), (55, 283), (55, 284), (55, 285), (55, 286), (55, 287),
(56, 288),
(57, 289), (57, 290), (57, 291), (57, 292), (57, 293), (57, 294), (57, 295), (57, 296), (57, 297), (57, 298),
(58, 299), (58, 300), (58, 301), (58, 302), (58, 303), (58, 304), (58, 305), (58, 306),
(59, 307), (59, 308), (59, 309), (59, 310), (59, 311), (59, 312),
(60, 313), (60, 314), (60, 315), (60, 316), (60, 317), (60, 318), (60, 319), (60, 320), (60, 321),
(61, 322), (61, 323), (61, 324),
(62, 325), (62, 326), (62, 327), (62, 328), (62, 329), (62, 330), (62, 331),
(63, 332), (63, 333), (63, 334), (63, 219), (63, 335), (63, 336), (63, 337), (63, 338), (63, 339),
(64, 340), (64, 341), (64, 342), (64, 343), (64, 344), (64, 345), (64, 346), (64, 347), (64, 348),
(65, 349), (65, 350), (65, 351), (65, 352),
(66, 353), (66, 354), (66, 355), (66, 356), (66, 357), (66, 358), (66, 359),
(67, 360), (67, 287), (67, 361), (67, 362),
(68, 363), (68, 364), (68, 365), (68, 366), (68, 367), (68, 368),
(69, 370), (69, 371), (69, 372), (69, 373),
(70, 374), (70, 375), (70, 376), (70, 377), (70, 378),
(71, 379), (71, 380), (71, 381), (71, 382), (71, 383),
(72, 384), (72, 385), (72, 386), (72, 387),
(73, 388), (73, 389), (73, 390), (73, 391), (73, 392), (73, 393), (73, 394),
(74, 395), (74, 396), (74, 397),
(75, 398), (75, 399), (75, 400), (75, 401), (75, 402), (75, 403), (75, 404),
(76, 405), (76, 406), (76, 407), (76, 408),
(77, 409), (77, 410), (77, 411), (77, 412),
-- Movie 78 (Shouta Goshozono id 153, Takahiro Sakurai id 155 có sẵn)
(78, 153), (78, 413), (78, 414), (78, 415), (78, 416), (78, 155),
(79, 417), (79, 418), (79, 419), (79, 420),
-- Movie 80 (Miyazaki Hayao id 384 dùng lại từ movie 72)
(80, 384), (80, 421), (80, 422), (80, 423),
-- Movie 81 (Quang Tuấn id 46, Quách Ngọc Ngoan id 84, Bích Ngọc id 26 có sẵn)
(81, 424), (81, 46), (81, 425), (81, 84), (81, 426), (81, 427), (81, 26), (81, 428), (81, 429), (81, 430), (81, 431), (81, 432), (81, 433),
(82, 434), (82, 435), (82, 436), (82, 437),
(83, 438), (83, 439), (83, 440), (83, 441);

SET FOREIGN_KEY_CHECKS = 1;

-- 69. Henrik Martin Dahlsbakken; Vivild Falk Berg, Vegard Strand Eide, Charlotte Frogner; Gia đình, Hài
-- 70. Nam Đoàn, Hậu Nguyễn; Hoàng Khuyết, Thùy Tiên, Trần Vũ; Hoạt Hình, Thần thoại
-- 71. Yaguchi Shinobu; Kôji Seto, Tetsushi Tanaka, Ken Yasuda, Jun Fubuki; Bí ẩn, Kinh Dị
-- 72. Miyazaki Hayao; Hitoshi Takagi, Noriko Hidaka, Chika Sakamoto; Hoạt Hình, Phiêu Lưu, Thần thoại
-- 73. Tom Gormican; Jack Black, Paul Rudd, Steve Zahn, Thandiwe Newton, Daniela Melchior, Selton Mello; Hài, Hành Động, Phiêu Lưu
-- 74. Azhar Lubis Kinois; Arifin Putra, Nayla D. Purnama; Kinh Dị
-- 75. HONG KI-WON; LEE JAE-IN, HONG KYUNG, JUNG MAN-SI, YU SU-BIN, KIM KUK-HEE, CHOI JUNG-UN; Hành Động, Hồi hộp
-- 76. Ding Zhong; Xin Li, Xiaoyu Liu, Tom Fu; Hoạt Hình, Khoa Học Viễn Tưởng, Phiêu Lưu
-- 77. Yonebayashi Hiromasa; Mirai Shida, Ryunosuke Kamiki, Tatsuya Fujiwara; Gia đình, Hoạt Hình, Thần thoại
-- 78. Shouta Goshozono; Junya Enoki, Yuma Uchida, Asami Seto, Yuichi Nakamura, Takahiro Sakurai; Hoạt Hình, Hành Động
-- 79. Tatsuya Yoshihara; Kikunosuke Toya, Tomori Kusunoki, Shôgo Sakata; Hành Động, Hoạt Hình, Thần thoại
-- 80. Miyazaki Hayao; Yasuo Yamada, Eiko Masuyama, Kiyoshi Kobayashi; Gia đình, Hoạt Hình, Phiêu Lưu
-- 81. Hoàng Tuấn Cường; Quang Tuấn, Hoài Lâm, Quách Ngọc Ngoan, Sỹ Toàn, Thanh Hương, Bích Ngọc, Lê Minh Thuấn, NSƯT Hạnh Thuý, Hoàng Yến, Lâm Thanh Sơn, Đình Hiếu, Hoàng Trinh; Hành Động, Tâm Lý
-- 82. Gang Zhang; Eric Bauza, Ben Diskin, Janice Kawaye; Gia đình, Hài, Hoạt Hình, Phiêu Lưu, Thần thoại